POST http://localhost:5000/api/contacts/
Content-Type: application/json

   {
       "name": "Caribou",
       "phone": "06 01 02 03 04"
   }

###

GET http://localhost:5000/api/contacts/
Content-Type: application/json

###

PUT http://localhost:5000/api/contacts/4
   Content-Type: application/json

   {
       "name": "Caribou2",
       "phone": "06 01 02 03 04"
   }

###

DELETE http://localhost:5000/api/contacts/4
   Content-Type: application/json

   {
       "name": "Caribou2",
       "phone": "06 01 02 03 04"
   }